In [1]:
import yfinance as yf
import pandas as pd
import numpy as np


def extract():
    ativos_escolhidos = ['^GSPC']
    periodo = 'max'

    dados_brutos = yf.download(
        ativos_escolhidos, period=periodo, auto_adjust=False)['Adj Close']
    dados_brutos.to_csv('dados_brutos.csv')
    print('Arquivo .csv criado')


if __name__ == '__main__':
    extract()

[*********************100%***********************]  1 of 1 completed

Arquivo .csv criado

In [2]:
import yfinance as yf
import pandas as pd



ativos_escolhidos = ['BTC-USD', 'BTLG11.SA', 'AAPL34.SA', 'PETR4.SA', 'LFTS11.SA', 'GOLD11.SA', '^BVSP', '^GSPC', 'B5P211.SA']
periodo = 'max'

dados_brutos = yf.download(ativos_escolhidos, period=periodo, auto_adjust=False)['Adj Close']
dados_brutos.head()

[*********************100%***********************]  9 of 9 completed

Ticker,AAPL34.SA,B5P211.SA,BTC-USD,BTLG11.SA,GOLD11.SA,LFTS11.SA,PETR4.SA,^BVSP,^GSPC
Date,,,,,,,,,
1927-12-30,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,17.660000
1928-01-03,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,17.760000
1928-01-04,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,17.719999
1928-01-05,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,17.549999
1928-01-06,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,17.660000

In [3]:
dados_limpos = dados_brutos.reset_index()
print(dados_limpos)

Ticker       Date  AAPL34.SA   B5P211.SA       BTC-USD   BTLG11.SA  GOLD11.SA  \
0      1927-12-30        NaN         NaN           NaN         NaN        NaN
1      1928-01-03        NaN         NaN           NaN         NaN        NaN
2      1928-01-04        NaN         NaN           NaN         NaN        NaN
3      1928-01-05        NaN         NaN           NaN         NaN        NaN
4      1928-01-06        NaN         NaN           NaN         NaN        NaN
...           ...        ...         ...           ...         ...        ...
26126  2026-03-19  65.000000  104.639999  69912.789062  103.570000  25.230000
26127  2026-03-20  66.120003  104.629997  70522.585938  103.169998  24.840000
26128  2026-03-21        NaN         NaN  68711.523438         NaN        NaN
26129  2026-03-22        NaN         NaN  67845.210938         NaN        NaN
26130  2026-03-23  65.980003  104.800003  70895.046875  103.440002  23.959999

Ticker   LFTS11.SA   PETR4.SA        ^BVSP        ^GSPC
0              NaN        NaN          NaN    17.660000
1              NaN        NaN          NaN    17.760000
2              NaN        NaN          NaN    17.719999
3              NaN        NaN          NaN    17.549999
4              NaN        NaN          NaN    17.660000
...            ...        ...          ...          ...
26126   149.830002  46.779999  180271.0000  6606.490234
26127   149.899994  45.669998  176219.0000  6506.479980
26128          NaN        NaN          NaN          NaN
26129          NaN        NaN          NaN          NaN
26130   149.990005  46.029999  181931.9375  6581.000000

[26131 rows x 10 columns]

In [4]:
dados_limpos.columns

Index(['Date', 'AAPL34.SA', 'B5P211.SA', 'BTC-USD', 'BTLG11.SA', 'GOLD11.SA',
       'LFTS11.SA', 'PETR4.SA', '^BVSP', '^GSPC'],
      dtype='object', name='Ticker')

In [5]:
dados_limpos.columns.tolist()

['Date',
 'AAPL34.SA',
 'B5P211.SA',
 'BTC-USD',
 'BTLG11.SA',
 'GOLD11.SA',
 'LFTS11.SA',
 'PETR4.SA',
 '^BVSP',
 '^GSPC']

In [6]:
dados_limpos = dados_limpos.melt(id_vars=['Date'], var_name='Ticker', value_name='Preço Ajustado')
print(dados_limpos)

             Date     Ticker  Preço Ajustado
0      1927-12-30  AAPL34.SA             NaN
1      1928-01-03  AAPL34.SA             NaN
2      1928-01-04  AAPL34.SA             NaN
3      1928-01-05  AAPL34.SA             NaN
4      1928-01-06  AAPL34.SA             NaN
...           ...        ...             ...
235174 2026-03-19      ^GSPC     6606.490234
235175 2026-03-20      ^GSPC     6506.479980
235176 2026-03-21      ^GSPC             NaN
235177 2026-03-22      ^GSPC             NaN
235178 2026-03-23      ^GSPC     6581.000000

[235179 rows x 3 columns]

In [7]:
dados_limpos['Retorno Diário'] = np.round(dados_limpos['Preço Ajustado'].pct_change()*100,2)

C:\Users\User\AppData\Local\Temp\ipykernel_6632\2752796292.py:1: FutureWarning: The default fill_method='pad' in Series.pct_change is deprecated and will be removed in a future version. Either fill in any non-leading NA values prior to calling pct_change or specify 'fill_method=None' to not fill NA values.
  dados_limpos['Retorno Diário'] = np.round(dados_limpos['Preço Ajustado'].pct_change()*100,2)

In [8]:
print(dados_limpos)

             Date     Ticker  Preço Ajustado  Retorno Diário
0      1927-12-30  AAPL34.SA             NaN             NaN
1      1928-01-03  AAPL34.SA             NaN             NaN
2      1928-01-04  AAPL34.SA             NaN             NaN
3      1928-01-05  AAPL34.SA             NaN             NaN
4      1928-01-06  AAPL34.SA             NaN             NaN
...           ...        ...             ...             ...
235174 2026-03-19      ^GSPC     6606.490234           -0.27
235175 2026-03-20      ^GSPC     6506.479980           -1.51
235176 2026-03-21      ^GSPC             NaN            0.00
235177 2026-03-22      ^GSPC             NaN            0.00
235178 2026-03-23      ^GSPC     6581.000000            1.15

[235179 rows x 4 columns]

In [9]:
dados_limpos = dados_limpos.dropna()

In [10]:
print(dados_limpos)

             Date     Ticker  Preço Ajustado  Retorno Diário
21264  2012-02-24  AAPL34.SA        1.330251            0.00
21265  2012-02-27  AAPL34.SA        1.330251            0.00
21266  2012-02-28  AAPL34.SA        1.330251            0.00
21267  2012-02-29  AAPL34.SA        1.391059            4.57
21268  2012-03-01  AAPL34.SA        1.396314            0.38
...           ...        ...             ...             ...
235172 2026-03-17      ^GSPC     6716.089844            0.25
235173 2026-03-18      ^GSPC     6624.700195           -1.36
235174 2026-03-19      ^GSPC     6606.490234           -0.27
235175 2026-03-20      ^GSPC     6506.479980           -1.51
235178 2026-03-23      ^GSPC     6581.000000            1.15

[53165 rows x 4 columns]

In [11]:
dados_limpos.groupby(['Ticker']).mean()

                                   Date  Preço Ajustado  Retorno Diário
Ticker
AAPL34.SA 2019-03-12 13:43:19.656946944       22.546386        0.132496
B5P211.SA 2023-07-22 02:08:44.718256896       82.700285        0.034959
BTC-USD   2020-06-19 12:00:00.000000000    27832.528733        0.262030
BTLG11.SA 2020-05-29 17:47:18.700760320       67.153036       -0.011123
GOLD11.SA 2023-08-06 12:53:51.755725312       13.412084        0.003366
LFTS11.SA 2025-03-04 13:37:44.627151104      131.345564        0.787208
PETR4.SA  2013-01-04 02:13:40.419325440        7.554733        0.075111
^BVSP     2009-10-12 07:41:44.405448704    53005.005318        0.125966
^GSPC     1977-03-11 08:19:47.159533088      728.531783        0.027056

In [12]:
dados_limpos.groupby(['Ticker'])[['Date','Retorno Diário']].max()

                Date  Retorno Diário
Ticker
AAPL34.SA 2026-03-23           20.69
B5P211.SA 2026-03-23            1.42
BTC-USD   2026-03-23          336.39
BTLG11.SA 2026-03-23            8.07
GOLD11.SA 2026-03-23            6.70
LFTS11.SA 2026-03-23          386.73
PETR4.SA  2026-03-23           22.22
^BVSP     2026-03-23           33.42
^GSPC     2026-03-23           16.61

In [13]:
ativos_escolhidos = ['AAPL34.SA','WEGE3.SA']
periodo = 'max'

dados_brutos = yf.download(
        ativos_escolhidos, period=periodo, auto_adjust=False)['Adj Close']
dados_brutos.to_csv('dados_brutos.csv')
print('Arquivo .csv criado')

[*********************100%***********************]  2 of 2 completed

Arquivo .csv criado

In [14]:
dados_brutos = pd.read_csv(
        'dados_brutos.csv', sep=',', decimal='.', index_col=0)
dados_limpos = dados_brutos.dropna()
dados_limpos = dados_limpos.reset_index()
dados_limpos = dados_limpos.melt(
    id_vars=['Date'], var_name='Ticker', value_name='Preço Ajustado')
dados_limpos['Retorno Diário'] = np.round(dados_limpos.groupby('Ticker')['Preço Ajustado'].pct_change()*100, 2)
dados_limpos = dados_limpos.dropna()
dados_limpos.to_csv('dados_limpos.csv', index=False)

In [15]:
dados_limpos.head()

         Date     Ticker  Preço Ajustado  Retorno Diário
1  2012-02-24  AAPL34.SA        1.330252            0.00
2  2012-02-27  AAPL34.SA        1.330252            0.00
3  2012-02-28  AAPL34.SA        1.330252            0.00
4  2012-02-29  AAPL34.SA        1.391059            4.57
5  2012-03-01  AAPL34.SA        1.396314            0.38

In [ ]:
dados_limpos = pd.read_csv('dados_limpos.csv')

            Date     Ticker  Preço Ajustado  Retorno Diário
0     2012-02-24  AAPL34.SA        1.330252            0.00
1     2012-02-27  AAPL34.SA        1.330252            0.00
2     2012-02-28  AAPL34.SA        1.330252            0.00
3     2012-02-29  AAPL34.SA        1.391059            4.57
4     2012-03-01  AAPL34.SA        1.396314            0.38
...          ...        ...             ...             ...
6991  2026-03-17   WEGE3.SA       46.099358            0.50
6992  2026-03-18   WEGE3.SA       46.059444           -0.09
6993  2026-03-19   WEGE3.SA       46.488506            0.93
6994  2026-03-20   WEGE3.SA       45.859879           -1.35
6995  2026-03-23   WEGE3.SA       47.250000            3.03

[6996 rows x 4 columns]

In [24]:
dados_limpos[:3]

         Date     Ticker  Preço Ajustado  Retorno Diário
1  2012-02-24  AAPL34.SA        1.330252             0.0
2  2012-02-27  AAPL34.SA        1.330252             0.0
3  2012-02-28  AAPL34.SA        1.330252             0.0

In [25]:
dados_limpos.head()

         Date     Ticker  Preço Ajustado  Retorno Diário
1  2012-02-24  AAPL34.SA        1.330252            0.00
2  2012-02-27  AAPL34.SA        1.330252            0.00
3  2012-02-28  AAPL34.SA        1.330252            0.00
4  2012-02-29  AAPL34.SA        1.391059            4.57
5  2012-03-01  AAPL34.SA        1.396314            0.38

In [26]:
dados_limpos.tail()

            Date    Ticker  Preço Ajustado  Retorno Diário
6993  2026-03-17  WEGE3.SA       46.099358            0.50
6994  2026-03-18  WEGE3.SA       46.059444           -0.09
6995  2026-03-19  WEGE3.SA       46.488506            0.93
6996  2026-03-20  WEGE3.SA       45.859879           -1.35
6997  2026-03-23  WEGE3.SA       47.250000            3.03

In [27]:
dados_limpos.columns

Index(['Date', 'Ticker', 'Preço Ajustado', 'Retorno Diário'], dtype='object')

In [32]:
dados_limpos.groupby('Ticker')['Retorno Diário'].describe()

            count      mean       std    min   25%   50%   75%    max
Ticker
AAPL34.SA  3498.0  0.132496  2.052892 -16.14 -0.82  0.00  1.00  20.69
WEGE3.SA   3498.0  0.108339  1.979175 -20.62 -0.96  0.04  1.12  13.89

In [35]:
dados_limpos[dados_limpos['Retorno Diário'] > 5]

            Date     Ticker  Preço Ajustado  Retorno Diário
18    2012-03-20  AAPL34.SA        1.647050           17.96
43    2012-04-25  AAPL34.SA        1.719117            5.05
67    2012-05-30  AAPL34.SA        1.743891            9.58
92    2012-07-05  AAPL34.SA        1.854996            5.24
109   2012-07-31  AAPL34.SA        1.870011            5.55
...          ...        ...             ...             ...
6333  2023-07-24   WEGE3.SA       38.462566            7.21
6476  2024-02-21   WEGE3.SA       34.043056            6.89
6571  2024-07-08   WEGE3.SA       41.797314            5.40
6588  2024-07-31   WEGE3.SA       47.615292           10.47
6769  2025-04-24   WEGE3.SA       46.332947            5.01

[104 rows x 4 columns]

In [36]:
dados_limpos['Retorno Diário'].mean()

0.12041738136077759

In [39]:
dados_limpos.groupby('Ticker')['Retorno Diário'].mean()

Ticker
AAPL34.SA    0.132496
WEGE3.SA     0.108339
Name: Retorno Diário, dtype: float64