In [5]:
import pandas as pd

In [9]:
#importar os dados do csv para ler com pandas e transformar em um DataFrame
df = pd.read_csv('bestsellers_with_categories.csv')

In [11]:
#Mostra as 5 primeiras linhas
df.head()

,Name,Author,User Rating,Reviews,Price,Year,Genre
0,10-Day Green Smoothie Cleanse,JJ Smith,4.7,17350,8,2016,Non Fiction
1,11/22/63: A Novel,Stephen King,4.6,2052,22,2011,Fiction
2,12 Rules for Life: An Antidote to Chaos,Jordan B. Peterson,4.7,18979,15,2018,Non Fiction
3,1984 (Signet Classics),George Orwell,4.7,21424,6,2017,Fiction
4,"5,000 Awesome Facts (About Everything!) (Natio...",National Geographic Kids,4.8,7665,12,2019,Non Fiction

In [12]:
df.count()

Name           550
Author         550
User Rating    550
Reviews        550
Price          550
Year           550
Genre          550
dtype: int64

In [ ]:
#Selecionar um tipo de dado
df[(df["User Rating"] > 4.8)]

In [ ]:
#Selecionar um tipo de dado
df[(df.Reviews > 1000) & (df.Year == 2019)]

In [ ]:
#criar um DataFrame. Passar um dicionário no dataframe, em que cada chave é o nome da coluna e a lista são os valores. as listas devem ter o mesmo tamanho
df1 = pd.DataFrame({
    'nome':['João', 'Maria', 'Pedro'],
    'endereço':['123 rua das tulipas', '123 ruas das rosas','123 rua das margaridas'],
    'idade':[34,28,51]
})
print(df1)

In [15]:
# Criar um DataFrame com listas
df2 = pd.DataFrame([
    ['João', 'Maria', 'Pedro'],
    ['123 rua das tulipas', '123 ruas das rosas','123 rua das margaridas'],
    [34,28,51]
],
columns=['Nome', 'Endereço', 'Idade'])

In [ ]:
#Ler o .csv
pd.read_csv('dados_limpos.csv')

#salvar como .csv
pd.to_csv('exemplo_novo_csv.csv')

In [ ]:
#Ler o csv e passar para uma variável
df = pd.read_csv('bestsellers_with_categories.csv')
print(df)

In [ ]:
df.head(15)

In [ ]:
df.info()

In [23]:
#Selecionar uma coluna:
df.Genre

0      Non Fiction
1          Fiction
2      Non Fiction
3          Fiction
4      Non Fiction
          ...
545        Fiction
546    Non Fiction
547    Non Fiction
548    Non Fiction
549    Non Fiction
Name: Genre, Length: 550, dtype: object

In [24]:
#Selecionar uma coluna também:
apenas_ticker = df['Author']

In [25]:
#aqui mostra que eu criei uma Series
print(type(apenas_ticker))

<class 'pandas.core.series.Series'>

In [26]:
#aqui mostra que eu criei um DataFrame
print(type(df))

<class 'pandas.core.frame.DataFrame'>

In [29]:
#Para selecionar duas ou mais colunas
duas_colunas = df[['Author', 'Reviews']]

In [ ]:
duas_colunas

In [ ]:
#selecionar linha
df.iloc[3]

In [ ]:
#Selecionar várias linhas
df.iloc[3:10]

In [34]:
#Selecionar usando lógica
df[df.Author == 'Amor Towles']

,Name,Author,User Rating,Reviews,Price,Year,Genre
7,A Gentleman in Moscow: A Novel,Amor Towles,4.7,19699,15,2017,Fiction

In [ ]:
df[(df['User Rating'] > 4.5) & (df['Year'] == 2014)]

In [ ]:
# & significa 'e' e | significa 'ou'
df[(df['Author'] =='Laura Hillenbrand') | (df['Year'] > 2018)]

In [ ]:
#Selecionar linhas que tenham vários argumentos
df[df.Author.isin(['Jen Sincero', 'Craig Smith'])]

In [41]:
#Para resetar o índice de um novo DataFrame, usa-se o .reset_index(). Isso cria um novo índice, mas o antigo vira uma nova coluna. 
#Para envitar isso, usar o argumento drop=True, dentro do método reset_index(), assim o antigo index é eliminado e o novo vira o index único.
novo_DF = df[(df['Year'] > 2017) & (df['User Rating'] > 4.6)]

In [ ]:
novo_DF

In [ ]:
novo_DF.reset_index()

In [ ]:
novo_DF.reset_index(drop=True)

In [ ]:
#Adicionar uma nova coluna. Você pode fornecer uma lista do mesmo tamanho das outras colunas. EX:
# df['Categoria'] = ['Romance', 'Ação', 'Aventura', 'Romance' ............]

In [ ]:
#Também pode adicionar uma coluna com algo igual para todas as linhas
df['Local de Venda'] = 'Amazon'

In [ ]:
df.head()

In [49]:
#Também pode adicionar uma coluna com alguma operação
df['Imposto de 10%'] = df['Price'] * 0.1

In [ ]:
df.head()

In [ ]:
df.Genre = df.Genre.apply(str.upper)
df.head()

In [ ]:
df.Genre = df.Genre.apply(str.lower)
df.head()

### Lambda

In [56]:
#Lambda com cálculos
my_lambda = lambda x: (x*2) + 3
print(my_lambda(15))

33

In [59]:
#Lambda para strings
stringlambda = lambda x: x.lower()
print(stringlambda('Oie, ComO VocÊ estÁ?'))

oie, como você está?

In [64]:
outra_lambda = lambda x: x[0] + x[-1]
print(outra_lambda("Como vai"))

Ci

In [66]:
#Função Lambda
# a estrutura geralmente é:
# lambda x : [OUTCOME IF TRUE] if [CONDITIONAL] else [OUTCOME IF FALSE]

In [70]:
#se fosse uma função. Ex horas extras acima de 40
def minha_funcao(x):
    if x > 40:
        return 40 + ((x - 40) * 1.5)
    else:
        return x
    
#quantas horas devo receber se trabalhar acima de 40?
print(minha_funcao(44))
print(minha_funcao(36))
print(minha_funcao(52))

46.0
36
58.0

In [73]:
#Se for pra fazer a mesma função como Lambda, fica:
horas_lambda = lambda x: 40 + ((x - 40) * 1.5) if x > 40 else x
print(horas_lambda(44))

46.0

In [74]:
#aplicar Lambda em colunas
df['Avaliação de 0 a 10'] = df['User Rating'].apply(lambda x: x * 2)
df

,Name,Author,User Rating,Reviews,Price,Year,Genre,Local de Venda,Imposto de 10%,Avaliação de 0 a 10
0,10-Day Green Smoothie Cleanse,JJ Smith,4.7,17350,8,2016,non fiction,Amazon,0.8,9.4
1,11/22/63: A Novel,Stephen King,4.6,2052,22,2011,fiction,Amazon,2.2,9.2
2,12 Rules for Life: An Antidote to Chaos,Jordan B. Peterson,4.7,18979,15,2018,non fiction,Amazon,1.5,9.4
3,1984 (Signet Classics),George Orwell,4.7,21424,6,2017,fiction,Amazon,0.6,9.4
4,"5,000 Awesome Facts (About Everything!) (Natio...",National Geographic Kids,4.8,7665,12,2019,non fiction,Amazon,1.2,9.6
...,...,...,...,...,...,...,...,...,...,...
545,Wrecking Ball (Diary of a Wimpy Kid Book 14),Jeff Kinney,4.9,9413,8,2019,fiction,Amazon,0.8,9.8
546,You Are a Badass: How to Stop Doubting Your Gr...,Jen Sincero,4.7,14331,8,2016,non fiction,Amazon,0.8,9.4
547,You Are a Badass: How to Stop Doubting Your Gr...,Jen Sincero,4.7,14331,8,2017,non fiction,Amazon,0.8,9.4
548,You Are a Badass: How to Stop Doubting Your Gr...,Jen Sincero,4.7,14331,8,2018,non fiction,Amazon,0.8,9.4
549,You Are a Badass: How to Stop Doubting Your Gr...,Jen Sincero,4.7,14331,8,2019,non fiction,Amazon,0.8,9.4

In [ ]:
#lambda para selecionar apenas o sobrenome
df['Sobrenome'] = df.Author.apply(lambda x: x.split(' ')[-1])
df

In [ ]:
#pode usar uma função lambda para uma linha inteira usando eow.column_name ou row['column_name]
# axis=1 aplica a função pras linhas
df['Classificação de nota'] = df.apply(lambda row:
    'Bem avaliado'
    if row['User Rating']  > 4.6
    else row['User Rating'],
    axis=1
)
df

### Renomeando Colunas

In [ ]:
#Renomear nome das colunas através da lista de nomes das colunas
exemplo_nome_colunas = pd.DataFrame({
    'name': ['John', 'Pedro', 'Paulo'],
    'age': [23,29,21]
})
exemplo_nome_colunas.columns = ['Nomes', 'Idade']
exemplo_nome_colunas

   Nomes  Idade
0   John     23
1  Pedro     29
2  Paulo     21

In [ ]:
#Renomear os nomes das colunas com .rename. usa o inplace=True para mudar o nomeno próprio dataframe e não no existente
exemplo_nome_colunas.rename(columns={
    'Nomes': 'Primeiro Nome',
    'Idade': 'Anos'},
    inplace=True
)
exemplo_nome_colunas

  Primeiro Nome  Anos
0          John    23
1         Pedro    29
2         Paulo    21

In [4]:
import datetime as datetime

datetime.now().strftime('%Y-%m-%d %H:%M:%S')

AttributeError: module 'datetime' has no attribute 'now'